import {StyleSheet} from 'react-native';

const styles = StyleSheet.create({
  hr: {
    height: 1,
    width: '100%',
    backgroundColor: '#d3d3d3',
  },
  container: {
    flex: 1,
    padding: 52,
    backgroundColor: '#FFF9EE',
    alignItems: 'center',
  },
  title: {
    fontSize: 36,
    fontWeight: '800',
    fontFamily: 'Barlow-Black',
    color: '#D4A817',
    marginVertical: 20,
  },
  subtitle: {
    fontSize: 32,
    fontFamily: 'BarlowCondensed-Medium',
    fontWeight: '600',
    color: '#000',
    marginBottom: 5,
    textAlign: 'center',
    lineHeight: 40,
  },
  image: {
    width: 150,
    height: 50,
    marginVertical: 20,
  },
  image_stage_one: {
    width: 203.27,
    height: 135.97,
    marginVertical: 0,
  },
  imageStageThree: {
    width: 232.5,
    height: 178.65,
    marginVertical: 20,
  },
  infoContainer: {
    width: '100%',
    padding: '5%',
    marginVertical: 20,
  },
  infoTitle: {
    fontSize: 14,
    fontWeight: '700',
    lineHeight: 16.8,
    fontFamily: 'Barlow-Black',
    color: '#000',
    marginTop: 10,
  },
  infoText: {
    fontSize: 12,
    fontFamily: 'Barlow-Thin',
    fontWeight: '400',
    lineHeight: 14.4,
    color: '#4D4D4D',
    marginVertical: 5,
  },
  progressContainerText: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  progressContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginVertical: 20,
    width: 100,
  },
  progressBar: {
    flex: 1,
    height: 10,
    backgroundColor: '#ECB64D',
    borderRadius: 10,
    marginRight: 10,
  },
  progress: {
    width: '33%',
    height: '100%',
    backgroundColor: '#5EB784',
    borderRadius: 10,
  },
  progressTwo: {
    width: '66%',
    height: '100%',
    backgroundColor: '#5EB784',
    borderRadius: 10,
  },
  progressThree: {
    width: '100%',
    height: '100%',
    backgroundColor: '#5EB784',
    borderRadius: 10,
  },
  stepText: {
    fontSize: 12,
    fontFamily: 'BarlowCondensed-Medium',
    fontWeight: '500',
    lineHeight: 14.4,
    color: '#000',
  },
  button: {
    backgroundColor: '#ECB64D',
    paddingVertical: 15,
    paddingHorizontal: 30,
    borderRadius: 8,
    marginVertical: 20,
    width: '100%',
  },
  buttonText: {
    color: '#000',
    fontSize: 16,
    fontWeight: '700',
    fontFamily: 'BarlowCondensed-Medium',
    alignSelf: 'center',
    lineHeight: 24,
  },
  loginLink: {
    marginVertical: 20,
  },
  loginText: {
    color: '#000',
    fontSize: 12,
    fontWeight: '400',
    fontFamily: 'Barlow-Thin',
    textDecorationLine: 'underline',
    lineHeight: 14.4,
  },
  instructionsContainer: {
    borderWidth: 1,
    borderColor: '#ECB64D',
    backgroundColor: '#FFF',
    padding: 10,
    borderRadius: 15,
    marginBottom: 20,
    width: '100%',
  },
  instructionsText: {
    fontFamily: 'BarlowCondensed-Medium',
    fontSize: 14,
    color: '#0E2B25',
    marginBottom: 5,
  },
  uploadContainer: {
    width: '100%',
    padding: 20,
    borderWidth: 1,
    borderColor: '#D1D1D1',
    backgroundColor: '#FBFBFB',
    borderRadius: 15,
    alignItems: 'center',
    marginBottom: 20,
    marginTop: 20,
  },
  uploadText: {
    fontFamily: 'BarlowCondensed-Medium',
    fontSize: 14,
    color: '#000',
    marginBottom: 10,
    lineHeight: 16.8,
  },
  uploadSubText: {
    fontFamily: 'Barlow-Thin',
    fontSize: 12,
    color: '#5F5F5F',
    marginBottom: 10,
    lineHeight: 14.4,
  },
  uploadButton: {
    backgroundColor: '#D4A817',
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderRadius: 5,
  },
  uploadButtonText: {
    color: '#FFF',
    fontSize: 16,
    lineHeight: 24,
    fontFamily: 'BarlowCondensed-Medium',
  },
  inputText: {
    color: '#000',
    fontSize: 12,
    lineHeight: 14.4,
    fontFamily: 'BarlowCondensed-Medium',
    padding: 10,
  },
  input: {
    width: '100%',
    padding: 10,
    fontFamily: 'Barlow-Thin',
    borderColor: '#ADADAD',
    borderWidth: 0,
    borderRadius: 8,
    marginBottom: 20,
    fontSize: 16,
    color: '#000',
    borderBottomWidth: 0.5,
  },
  infoItem: {
    marginBottom: 20,
  },
  linkText: {
    width: 289,
    height: 14,
    fontSize: 12,
    lineHeight: 14.4,
    fontFamily: 'BarlowCondensed-Medium',
    color: '#000',
    textDecorationLine: 'underline',
    marginVertical: 10,
  },
  denyLink: {
    marginVertical: 20,
  },
  denyText: {
    color: '#000',
    fontSize: 14,
    textDecorationLine: 'underline',
  },
});

export default styles;
